---
- name: Harden system
  hosts: all
  become: true
  handlers:
    - name: Restart SSH daemon
      ansible.builtin.service:
        name: sshd
        state: restarted

  pre_tasks:
    - name: Configure SSH options
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication yes'
        - regexp: '^PermitRootLogin'
          line: 'PermitRootLogin yes'
      notify: Restart SSH daemon

  post_tasks:
    - name: Enable firewall
      ansible.builtin.include_tasks: firewall.yml

    - name: Enable SELinux
      ansible.builtin.include_tasks: selinux.yml

    - name: Install and configure fail2ban
      ansible.builtin.include_tasks: fail2ban.yml

    - name: Install and configure AIDE
      ansible.builtin.include_tasks: aide.yml

  roles:
    - role: devsec.hardening.os_hardening
