---
- name: Harden system
  hosts: all
  become: true
  tasks:
    - name: Install web application
      ansible.builtin.include_tasks: web.yml

  post_tasks:
    - name: Enable firewall
      ansible.builtin.include_tasks: firewall.yml

    - name: Enable SELinux
      ansible.builtin.include_tasks: selinux.yml

    - name: Install and configure fail2ban
      ansible.builtin.include_tasks: fail2ban.yml

    - name: Install and configure AIDE
      ansible.builtin.include_tasks: aide.yml

  roles:
    - role: devsec.hardening.os_hardening
